#!/usr/bin/env bash

PROJECT=YOUR_PROJECT_NAME_HERE
PROXY_SERVICE_NAME=YOUR_PROXY_SERVICE_NAME_HERE
PROXY_CONFIG_GCS_PATH=gs://YOUR_DEPLOY_BUCKET_NAME_HERE/config.txt
PROXY_SA_KEY_GCS_PATH=gs://YOUR_DEPLOY_BUCKET_NAME_HERE/privatekey.json