runtime: python37

instance_class: F2

inbound_services:
  - warmup

env_variables:
  IDC_THROTTLE_PROXY_CONFIG: ./config.txt

service: proxy

handlers:
  - url: /.*
    script: auto
    secure: always
  - url: .*
    script: auto

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: 0.030s
  max_pending_latency: automatic
  max_concurrent_requests: 20
  target_cpu_utilization: 0.65
  min_instances: 3
  max_instances: 100

vpc_access_connector:
  name: 'projects/<project-id>/locations/<location>/connectors/redis-connector'

network:
  instance_tag: default

