runtime: python37

instance_class: F2

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: ./privatekey.json
  IDC_THROTTLE_PROXY_CONFIG: ./config.txt

service: default

handlers:
- url: /.*
  script: auto
  secure: always

vpc_access_connector:
  name: 'projects/idc-sandbox-002/locations/us-central1/connectors/redis-connector'

network:
  instance_tag: idc-default

